### ISSUE TITLE
error initializing module

### ISSUE THREAD

**Issue by aralisa11** [Shinoyx/rk9guide#4]
Hey. Wanted to try your module but unfortunately got a problem with it. Is there any way to fix this? 

[22:02:56 GMT+0200] ERROR tera-proxy: failed to preload module (module = rk9guide-master)
Error: Cannot find module 'command'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\fairl\Desktop\tera-proxy\bin\node_modules\rk9guide-master\index.js:4:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

[21:56:16 GMT+0200] ERROR tera-proxy-game: [dispatch] load: error initializing module "rk9guide-master"
error: Cannot find module 'command'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)

**Comment by russopie** [comment]
you need this module https://github.com/pinkipi/command many modules are dependent of this one, download and put in same place of rk9 module

**Comment by aralisa11** [comment]
Okay, so I did as you said but it still doesn't work for me.

**Comment by russopie** [comment]
same error? try to get last proxy version from here: https://discord.gg/mrFpeV

**Comment by aralisa11** [comment]
now I'm not even sure if proxy works, shows me something like this:

[proxy] preloading modules
[sls] server list overridden
[game] listening on 127.0.0.20:9250
[game] listening on 127.0.0.20:9251
[game] listening on 127.0.0.20:9252
[game] listening on 127.0.0.20:9253
[game] listening on 127.0.0.20:9254

**Comment by russopie** [comment]
it's ok, preloading modules message, after you have logged in proxy window will show wich modules were successfully loaded

**Comment by aralisa11** [comment]
the problem is, this message doesn't change even after I've logged in, not sure how long I should wait for it to load

**Comment by russopie** [comment]
It shows up immediately after you have logged

**Comment by aralisa11** [comment]
well, it doesn't for me, maybe this proxy version just doesn't work for RU tera

**Comment by Shinoyx** [comment]
@aralisa11 go to your proxyfolder -> bin -> config.json -> edit that file to RU server
